services:
  dev:
    build:
      context: .
      target: dev
    container_name: lights-out-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  prod:
    build:
      context: .
      target: prod
    container_name: lights-out-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    profiles:
      - prod
